# Generated by Django 5.2.6 on 2025-09-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='location',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
